services:
  - type: web
    name: panini-album
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
